version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.2
    - 3.6.3
  - dependency-name: karma
    versions:
    - 5.2.3
    - 6.0.3
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@angular/animations"
    versions:
    - 11.0.5
  - dependency-name: lint-staged
    versions:
    - 10.5.3
