FROM acklenavenue/angular-cli_chrome

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY . .
RUN apt-get update
RUN npm install
RUN npm i -g gulp 

EXPOSE 4200
CMD [ "echo", "frontend" ]
