FROM node:8.8.1

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY . .
RUN apt-get update
RUN npm i -g gulp 
RUN npm install

EXPOSE 4200
CMD [ "echo", "frontend" ]